{% set name = "bc-python-hcl2" %}
{% set version = "0.3.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bc-python-hcl2-{{ version }}.tar.gz
  sha256: 15bfecbae882ead998dd9300737237a14e40dfd8c973e5c7de7b4c92040a010f

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  run:
    - python
    - lark >=1.0.0
    - importlib-resources >=2.0.0  # [py<39]

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
